[versions]

kotlinJvm = "1.8.21"
intellijPlgn = "1.13.3"

[libraries]

[plugins]

kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvm" }
intellijPlgn = { id = "org.jetbrains.intellij", version.ref = "intellijPlgn" }
