[versions]

kotlinJvm = "1.8.21"
intellijPlgn = "1.17.4"
arrowKt = "1.2.4"

[libraries]

kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test" }
arrow-core = { group = "io.arrow-kt", name = "arrow-core", version.ref = "arrowKt" }

[plugins]

kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvm" }
intellijPlgn = { id = "org.jetbrains.intellij", version.ref = "intellijPlgn" }
